### ISSUE TITLE
Default settings for ampslice and ampgate?

### ISSUE THREAD

**Issue by rconstanzo** [jamesb93/ReaCoMa#2]
So I've tried running every possible sound in the universe on these algorithms and never get any slices from it. I noticed that in the video you used some different default settings. Is there any chance those can be baked in?

**Comment by jamesb93** [comment]
I decided to copy the defaults of the command line objects, but I agree the defaults are obscure in their intention. What would be your proposed defaults?

**Comment by rconstanzo** [comment]
For `ampslice` some modest "general purpose" settings could be:
`@highpassfreq 110 @floor -70 @fastrampup 5 @fastrampdown 500 @slowrampup 2205 @slowrampdown 2205 @minslicelength 4410 @onthreshold 11 @offthreshold 5`

For `ampgate` that one is trickier because of the absolute thresholds, but taking a cue from the `fluid.ampgate~` helpfile you can do this:
`@onthreshold -27 @offthreshold -31 @rampup 441 @rampdown 4410 @minsilencelength 4410 @highpassfreq 20`

The `ampslice` one I'm fairly confident would work on "most" material. The `ampgate` one is completely dependent on the amplitude of the signal, but it's easier to mess around two numbers rather than 15.
