### ISSUE TITLE
BALKIN AT WAV

### ISSUE THREAD

**Issue by tinpark** [jamesb93/ReaCoMa#7]
Hi James, this is a fun one. If you've got a perfectly OK `.wav` file, but it was recorded say on a zoom recorder and therefore, it's been named `.WAV` rather than `.wav`, the scripts won't run. 

At least, that's the situ on both of my windows and mac boxes. The same sort of file works on the commandline regardless of whether the case is `.wav` or `.WAV`. Renaming to `.wav` and things work fine. This isn't a problem really, but it may catch some people out so it would be great if .WAV and .AIF and .AIFF could be allowed as possible file extensions in the `.lua` scripta to save some people heartache in the future perhaps. Cheers Martin~

**Comment by jamesb93** [comment]
Nice one, .WAV is pretty gangaster but perfectly valid so it shouldn't complain. I'm coding some other stuff now in preperation for tomorrow but I'm going to push some fixes as a batch soon.

**Comment by jamesb93** [comment]
Sorry for the massive delay, this is fixed now in https://github.com/jamesb93/ReaCoMa/releases/tag/1.5.4
